### ISSUE TITLE
Stops receiving new events failing with the same error over and over

### ISSUE THREAD

**Issue by felipetavares** [lluchs/eventsource#1]
I am collecting events from the Wikimedia streaming API. After a while (around half-million events), the stream fails with the same error over and over:

> Invalid chunk size lineobs: 17

I am currently trying to read the source and find out what is happening , but any pointers would be appreciated.

**Comment by felipetavares** [comment]
Got the same state, but with another message this time (and a lot fewer events):

> Event error: Invalid chunk size line

I think the problem is that somehow when this error happens, we keep trying to read from the same buffer instead of retrying the download. I am not familiar with how SSE works at low leve, but I'll look into that.

**Comment by lluchs** [comment]
I suspect the error is happening here:

https://github.com/lluchs/eventsource/blob/22d8423c35af800695dbe7d16b69d0e6cb928e56/src/reqwest.rs#L133

Instead of just returning the error via the try macro, the code should also set self.response to None so that the next iteration starts a new request.

**Comment by felipetavares** [comment]
I am testing with a quite hacky solution (I could not think of anything else without changing the loop structure quite a bit).

I made this macro to break from the loop instead of returning:

```rust
macro_rules! try_option_break {
    ($e:expr, $lbl:tt) => (match $e {
        Ok(val) => val,
        Err(_) => break $lbl,
    });
}
```

And applied like this:

```rust
'parse: while try_option_break!(reader.read_line(&mut line), 'parse) > 0 {
```

I am now checking if it fixes the issue, if it does I will try to restructure the loop into a `loop` to allow me to break returning the err.

**Comment by felipetavares** [comment]
Definitely fixed!

**Comment by felipetavares** [comment]
@lluchs finished the PR, can you review it/merge?

**Comment by lluchs** [comment]
Thanks! I also updated reqwest which changed the return value of `Client::new()`. Should be easy to upgrade, though.

**Comment by felipetavares** [comment]
That's great, no worries!

**Comment by felipetavares** [comment]
@lluchs Any luck?

**Comment by lluchs** [comment]
Sorry, I was on vacation. I managed to upload the crate now from a different network.
